# POST  http://localhost:3001/api/persons
# Content-Type: application/json

# {
#     "name": "a",
#     "number":"911",
#     "id":7
# }

POST http://localhost:3001/api/persons
Content-Type: application/json

{"name":"a","number":"100","id":290}